name: dev_pyhecdss
channels:
  - cadwr-dms
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - ipykernel # for jupyter notebook support
  - black # for formatting esp. in jupyter notebook
  - numpy
  - pandas
  - pytest
  - conda-build
  - nbsphinx # docs stuff below
  - sphinx
  - pandoc
