#ifndef __HECLIB_INCLUDED__
#define __HECLIB_INCLUDED__

#ifdef __cplusplus
extern "C" {
#endif

#ifdef SWIG
	#define long_long long long
#elif defined(_MSC_VER)
        #if _MSC_VER < 1400
                typedef __int64 long_long;
        #else
                typedef long long long_long;
        #endif
        #ifdef _WIN64
                typedef long long slen_t;
        #else
                typedef int slen_t;
        #endif
#else
        typedef long long long_long;
        typedef int slen_t;
#endif

/*------------------*/
/* Fortran routines */
/*------------------*/
void      abort_(void);
void      addcentury_(int *iyear);
void      anread_(int *iunit, char *cpromp, int *npromp, char *cline, int *nline, slen_t _cpromp_len, slen_t _cline_len);
void      anrout_(int *iounit);
void      asctrl_(int *iunit, char *cfun, int *iarg1, int *iarg2, slen_t _cfun_len);
void      attach_(int *iunit, char *ckywrd, char *cdfalt, char *contrl, char *cname, int *istat, slen_t _ckywrd_len, slen_t _cdfalt_len, slen_t _contrl_len, slen_t _cname_len);
void      attcrk_(char *cleft, char *cright, int *jks, int *ks, int *istat, slen_t _cleft_len, slen_t _cright_len);
void      attdcd_(char *contrl, char *cstat, int *nbit, char *caccs, int *nlen, char *ctype, char *cform, char *cmode, char *cprmp, char *cnop, int *istdot, slen_t _contrl_len, slen_t _cstat_len, slen_t _caccs_len, slen_t _ctype_len, slen_t _cform_len, slen_t _cmode_len, slen_t _cprmp_len, slen_t _cnop_len);
void      attend_(void);
void      attmat_(char *ckyary, char *ckywrd, int *ien, int *jks, int *ks, int *jsub, slen_t _ckyary_len, slen_t _ckywrd_len);
void      attopn_(int *iunit, char *ckywrd, char *cname, int *istdin, int *istdot, char *cstat, int *nbit, char *caccs, int *nlen, char *ctype, char *cform, char *cmode, int *linac, int *ldfalt, int *istat, slen_t _ckywrd_len, slen_t _cname_len, slen_t _cstat_len, slen_t _caccs_len, slen_t _ctype_len, slen_t _cform_len, slen_t _cmode_len);
void      attset_(char *clin, slen_t _clin_len);
void      attsub_(char *cdfalt, char *cdfsub, int *ndfalt, slen_t _cdfalt_len, slen_t _cdfsub_len);
void      bits_(int *iarray, int *ibitno, int *iset, int *lget);
void      bkdatw_(void);
void      cdate_(char *carray, slen_t _carray_len);
void      cdelet_(char *cname, int *ierr, slen_t _cname_len);
void      ch2hol_(char *chr, int *ihol, int *nwords, slen_t _chr_len);
void      chdlm_(int *itype, char *cstrng, int *ibeg, int *numb, int *itbl, slen_t _cstrng_len);
void      chgtyp_(float *r1, float *r2);
void      chrblk_(char *cstr, slen_t _cstr_len);
void      chrfil_(char *cline, char *chr, slen_t _cline_len, slen_t _chr_len);
void      chrfl1_(void);
void      chrflb_(char *cstring, int *ibeg, int *iend, slen_t _cstring_len);
void      chrhol_(char *c, int *is, int *nc, int *ic, int *js, slen_t _c_len);
void      chrint_(int *numb, char *cstring, slen_t _cstring_len);
void      chrlnb_(char *cline, int *ilast, slen_t _cline_len);
void      chrwt1_(char *cstr, int *nstr, slen_t _cstr_len);
void      chrwt_(int *klfn, char *cstr, int *nstr, slen_t _cstr_len);
void      cjchr_(char *cline, slen_t _cline_len);
void      cjstr_(char *cstr1, int *nbeg1, int *nlen1, char *cstr2, int *nbeg2, slen_t _cstr1_len, slen_t _cstr2_len);
void      ckansi_(int *iunit, int *lansi);
void      clines_(int *nlines);
void      clktime_(char *carray, slen_t _carray_len);
void      cparms_(char *cline, int *nchs, slen_t _cline_len);
void      crenam_(char *coldnm, char *cnewnm, int *ierr, slen_t _coldnm_len, slen_t _cnewnm_len);
void      ctime_(char *carray, slen_t _carray_len);
void      curtim_(int *jul, int *min);
void      datcll_(int *julin, int *intime, int *julout, int *ioutim);
void      datcln_(int *julin, int *intime, int *julout, int *ioutim);
void      datime_(int *jyr, int *nday, int *j10sec);
void      datjul_(char *cdate, int *jul, int *ierr, slen_t _cdate_len);
void      datymd_(char *cdate, int *iyr, int *imon, int *iday, int *ierr, slen_t _cdate_len);
void      dcdltr_(float *r1, int *nr1, int *iprec, float *base, int *lbase, int *icmval, int *ncmval, int *kcmval, int *ibbyte, int *isize, int *istat);
void      dcinfo_(int *ih, int *nh, int *ibgelm, int *nelms, int *istwrd, int *nwords, int *ibbyte);
void      dcreal_(float *r, int *nr, int *iskm, float *base, int *lbase, int *isize, int *iprec, int *icmval, int *ncmval, int *kcmval, int *ih, int *nh, int *kh, int *istat);
void      dcrept_(float *r1, int *nr1, float *r2, int *nr2, int *i1, int *ni1, int *ki1, int *istat);
void      dcsd3r_(float *r1, int *nr1, int *icmval, int *ncmval, int *kcmval, int *ibbyte, int *istat);
void      dhchek_(int *istbyt, int *ih, int *nh, int *istat);
void      dhinfo_(int *ih, int *nh, int *iskm, int *nr2, float *base, int *lbase, int *nelms, int *isize, int *iprec, int *lrpeat, int *ldelta, int *lsigdt, int *istat);
void      dhinit_(float *base, int *ibase, int *nbase, int *ih, int *nh, int *iprec, int *isize, int *iskm, int *nbits, int *nbytes, int *nelms, int *istat, int *lbase, int *ldelta, int *lsigdt);
void      dibin_(int *iunit, int *numb);
void      dmreal_(float *r, int *ibgelm, int *nelms, int *icmval, int *ncmval, int *kcmval, int *ih, int *nh, int *istat, int *iskm);
void      dudltr_(float *r1, int *nr1, int *iprec, float *base, int *lbase, int *icmval, int *ncmval, int *ibbyte, int *isize, int *istat);
void      dureal_(float *r, int *kr, int *ibgelm, int *nelms, int *icmval, int *ncmval, int *kcmval, int *ih, int *nh, int *istat);
void      durept_(float *r1, int *nr1, float *r2, int *nr2, int *i1, int *ni1, int *istat);
void      dusd3r_(float *r1, int *nr1, int *icmval, int *ncmval, int *ibbyte, int *istat);
void      findlm_(char *ca, int *ka, int *na, int *nf, int *ibf, int *ilf, int *idt, int *idp, int *itbl, slen_t _ca_len);
int       fortranclose_(int *iunit);
void      fortranflush_(int *iunit);
int       fortranopen_(int *iunit, char *filename, slen_t _filename_len);
int       fortranwrite_(int *iunit, char *string, slen_t _string_len);
void      getbin_(int *jwords, int *nbytes, char *crepr, slen_t _crepr_len);
void      gethol_(int *istr, int *ipos, int *ich);
void      getime_(char *cin, int *ibline, int *lenlin, int *juls, int *istime, int *jule, int *ietime, int *istat, slen_t _cin_len);
void      getnam_(int *ilfn, char *cname, int *iflag, slen_t _cname_len);
void      gnumrg_(char *cname, int *nrange, int *nvalue, int *istat, slen_t _cname_len);
void      gstrrg_(char *cname, char *cstr, int *nstr, int *istat, slen_t _cname_len, slen_t _cstr_len);
void      gtcopt_(char *cline, char *copt, int *nchrs, slen_t _cline_len, slen_t _copt_len);
void      hol2ch_(int *ihol, char *chr, int *nwords, slen_t _chr_len);
void      holchr_(int *ic, int *is, int *nc, char *c, int *js, slen_t _c_len);
long_long i4toi8_(int *i4);
int       i8toi4_(long_long *i8);
int       ibits_(int *iw, int *ibit, int *nbits);
int       icentury_(void);
int       ictime_(int *jul1, int *itime1, int *jul2, int *itime2);
int       idaywk_(int *jul);
int       ihm2m_(char *ctime, slen_t _ctime_len);
int       ihms2s_(char *ctime, slen_t _ctime_len);
int       inctim_(int *interval, int *mindayflag, int *nperiods, int *juls, int *istime, int *jule, int *ietime);
int       indexr_(char *cstr1, char *cstr2, slen_t _cstr1_len, slen_t _cstr2_len);
int       intchr_(char *cstring, slen_t _cstring_len);
int       intgr_(char *cline, int *nbeg, int *nlen, int *ierr, slen_t _cline_len);
void      intgrc_(int *numb, char *cline, int *nbeg, int *nlen, slen_t _cline_len);
int       iscan_(char *cstr1, int *nbeg1, int *nlen1, char *cstr2, int *nbeg2, int *nlen2, int *ipos2, slen_t _cstr1_len, slen_t _cstr2_len);
int       iymdjl_(int *iyr, int *imon, int *iday);
int       jliymd_(int *jul, int *iyr, int *imon, int *iday);
void      juldat_(int *jul, int *istyle, char *cdate, int *ndate, slen_t _cdate_len);
int       lbtest_(int *iw, int *ibit);
int       lcompar_(float *svalues, float *dvalues, int *ipos, int *ldouble, float *val);
int       lcopts_(char *copts, char *chr, slen_t _copts_len, slen_t _chr_len);
int       leqner_(float *x, float *y, float *tol);
int       leqnerd_(double *x, double *y, float *tol);
void      lflnb_(char *cline, int *nbeg, int *nlen, int *ibegnb, int *ilennb, slen_t _cline_len);
int       lgener_(float *x, float *y, float *tol);
int       lgtner_(float *x, float *y, float *tol);
int       lisfil_(char *str, slen_t _str_len);
int       lisnum_(char *cstrng, slen_t _cstrng_len);
void      ljchr_(char *cline, int *nline, slen_t _cline_len);
void      ljstr_(char *cstr1, int *nbeg1, int *nlen1, char *cstr2, int *nbeg2, slen_t _cstr1_len, slen_t _cstr2_len);
int       llener_(float *x, float *y, float *tol);
int       lltner_(float *x, float *y, float *tol);
void      locase_(char *cline, slen_t _cline_len);
int       lpopt_(char *copt, slen_t _copt_len);
int       m2ihm_(int *min, char *ctime, slen_t _ctime_len);
void      match_(char *cstr, int *ibeg, int *ilen, char *clist, int *nlist, int *nlen, int *imatch, slen_t _cstr_len, slen_t _clist_len);
int       messag_(int *iunit, int *iout, char *cname, slen_t _cname_len);
void      mvbits_(int *iw, int *ib, int *nb, int *jw, int *jb);
void      namfil_(int *ifn, char *cnames, int *inames, int *max, int *istat, slen_t _cnames_len);
void      namlst_(char *cnames, int *inames, slen_t _cnames_len);
int       nindx_(char *cstr1, char *cstr2, slen_t _cstr1_len, slen_t _cstr2_len);
int       nindxr_(char *cstr1, char *cstr2, slen_t _cstr1_len, slen_t _cstr2_len);
int       nopers_(int *interval, int *mindayflag, int *juls, int *istime, int *jule, int *ietime);
int       nscan_(char *cstr1, int *nbeg1, int *nlen1, char *cstr2, int *nbeg2, int *nlen2, slen_t _cstr1_len, slen_t _cstr2_len);
void      nserch_(char *cnam, int *loc, char *cnames, int *inames, slen_t _cnam_len, slen_t _cnames_len);
int       numlin_(char *cfname, slen_t _cfname_len);
void      panred_(int *iunit, char *cpromp, int *npromp, char *cline, int *nline, slen_t _cpromp_len, slen_t _cline_len);
void      parseq_(char *cline, int *maxf, int *nfield, char *clettr, int *ibf, int *ief, int *ilf, slen_t _cline_len, slen_t _clettr_len);
void      parsli_(char *cline, int *maxf, int *nfield, int *ibf, int *ief, int *ilf, slen_t _cline_len);
void      pattch_(int *iunit, char *ckey, char *cdef, char *contrl, char *cstr, int *istat, slen_t _ckey_len, slen_t _cdef_len, slen_t _contrl_len, slen_t _cstr_len);
void      pcdlin_(void);
void      pdisp_(char *op, char *copt, int *up, slen_t _op_len, slen_t _copt_len);
void      pedit_(void);
void      pend_(void);
void      perr_(void);
void      pexlin_(void);
void      pfind_(int *lfn, char *string, int *line1, int *up, int *found, int *idsp, slen_t _string_len);
void      pfnkey_(char *cnkey, char *cstrng, int *ns, slen_t _cnkey_len, slen_t _cstrng_len);
void      pgfscn_(float *cfield, float *cfmt, int *ival);
void      pgtlin_(int *leof);
void      pinqir_(char *cinstr, char *cpram, int *npram, slen_t _cinstr_len, slen_t _cpram_len);
void      pitab_(void);
void      pldfun_(int *istat);
void      pldmac_(char *cname, int *istat, slen_t _cname_len);
void      pldscn_(char *cscrn, slen_t _cscrn_len);
void      pmain_(int *iscrt, char *clin1, char *clin2, int *ientry, slen_t _clin1_len, slen_t _clin2_len);
void      pmcsub_(char *mastxt, char *partxt, int *parcnt, int *parstr, int *parlen, char *subtxt, int *subcnt, int *substr, int *sublen, slen_t _mastxt_len, slen_t _partxt_len, slen_t _subtxt_len);
void      pnxtln_(int *k, int *iss, int *nl, int *nlx, int *ml, int *mlx, char *clinx, int *lend, slen_t _clinx_len);
void      posfl_(int *iunit, int *iline, int *istat);
void      prdmen_(char *c, int *i, slen_t _c_len);
void      pread1_(char *clin1, slen_t _clin1_len);
void      pread2_(char *clin1, char *clin2, slen_t _clin1_len, slen_t _clin2_len);
void      pread_(int *iscrt);
void      preadc_(int *iscrt, char *clin1, int *ientry, void *return_1, slen_t _clin1_len);
void      prstat_(int *lflag, char *chcom, char *chfunc, slen_t _chcom_len, slen_t _chfunc_len);
void      prtary_(float *array, int *narray);
void      prtwrd_(int *iaddr, int *nwords, int *lhead);
void      pscatt_(char *catt, char *cscn, int *isatt, int *iline, int *nline, int *iofset, int *ipstat, slen_t _catt_len, slen_t _cscn_len);
void      pschin_(float *cline, int *nnchr, int *lmatch);
void      pset_(char *cinstr, char *cpram, int *npram, slen_t _cinstr_len, slen_t _cpram_len);
void      psetfn_(char *cinkey, char *cstrng, int *nstrng, slen_t _cinkey_len, slen_t _cstrng_len);
void      psfscn_(int *ival);
void      pslmen_(char *c1, char *c2, int *i, slen_t _c1_len, slen_t _c2_len);
void      pslscn_(int *lresp);
void      pttach_(int *iunit, char *ckey, char *cdef, char *contrl, char *cstr, int *istat, slen_t _ckey_len, slen_t _cdef_len, slen_t _contrl_len, slen_t _cstr_len);
void      puthol_(int *istr, int *ipos, int *ich);
void      r2sd3_(float *r, int *i2);
void      rattim_(char *cstr, int *nstr, int *rtime, int *istat, slen_t _cstr_len);
void      rbell_(void);
void      remblk_(char *cin, char *cout, int *nout, slen_t _cin_len, slen_t _cout_len);
void      rjchr_(char *cline, slen_t _cline_len);
void      rjstr_(char *cstr1, int *nbeg1, int *nlen1, char *cstr2, int *nbeg2, slen_t _cstr1_len, slen_t _cstr2_len);
void      scnchk_(char *c, int *i, int *l, slen_t _c_len);
void      sd32r_(int *i2, float *r);
void      setdlm_(int *itype, char *cstrng, int *ibeg, int *numb, int *itbl, slen_t _cstrng_len);
void      setnam_(char *cpsudo, char *ctrue, int *max, char *cnames, int *inames, int *ilistl, int *istat, slen_t _cpsudo_len, slen_t _ctrue_len, slen_t _cnames_len);
void      snumrg_(char *cname, int *nrange, int *nvalue, int *istat, slen_t _cname_len);
void      sstrrg_(char *cname, char *cstr, int *nstr, int *istat, slen_t _cname_len, slen_t _cstr_len);
void      stdinc_(char *cwait, char *cecho, char *cbreak, char *cflush, int *iascii, int *icode, slen_t _cwait_len, slen_t _cecho_len, slen_t _cbreak_len, slen_t _cflush_len);
void      stuffuserheader_(char *label, char *item, float *ruhead, int *kuhead, int *nuhead, int *istat, slen_t _label_len, slen_t _item_len);
void      subdat_(char *cline, slen_t _cline_len);
void      tempname_(char *cname, int *iunit, slen_t _cname_len);
void      trunam_(char *cpsudo, char *ctru, char *cnames, int *inames, slen_t _cpsudo_len, slen_t _ctru_len, slen_t _cnames_len);
void      txtcol_(char *cfgin, char *cbgin, char *cattin, slen_t _cfgin_len, slen_t _cbgin_len, slen_t _cattin_len);
void      unstuffuserheader_(char *label, char *item, int *ipos, float *ruhead, int *nuhead, int *istat, slen_t _label_len, slen_t _item_len);
void      upcase_(char *cline, slen_t _cline_len);
void      vansi_(int *idsp);
void      vatt_(int *iatt);
void      vend_(void);
void      verase_(void);
void      verasg_(void);
void      vinit_(int *jdsp);
void      vmovcr_(int *irp, int *icp);
void      vset_(char *cmode, char *cspec, slen_t _cmode_len, slen_t _cspec_len);
void      vwtla_(char *cl, int *iatt, int *irow, int *icol, slen_t _cl_len);
void      wait_(int *i1, int *i2, int *i3);
void      when_(char *cdat, char *ctim, slen_t _cdat_len, slen_t _ctim_len);
void      wind_(int *ilfn);
void      xqtlne_(char *cline, int *nchs, slen_t _cline_len);
float     xreal_(char *cline, int *nbeg, int *nlen, int *ierr, slen_t _cline_len);
void      xrealc_(float *xnumb, char *cline, int *nbeg, int *nlen, int *ndec, slen_t _cline_len);
double    xreald_(char *cline, int *nbeg, int *nlen, int *ierr, slen_t _cline_len);
void      ymddat_(int *iyr, int *imon, int *iday, int *istyle, char *cdate, int *ndate, int *ierr, slen_t _cdate_len);
void      zabort_(int *ifltab, int *ierr, char *csub, int *jerr, int *iadd, char *ccomet, slen_t _csub_len, slen_t _ccomet_len);
void      zbdump_(int *ifltab, int *ibgbuf);
void      zbegdt_(int *jul, int *intl, int *iyr, int *imon, int *iday, int *iblock, int *iverno);
void      zcaout_(int *ifltab, int *icunit, int *icdunt, int *lcdcat, int *norecs);
void      zcat_(int *ifltab, int *icunit, int *icdunt, int *inunit, char *cinstr, int *labrev, int *ldosrt, int *lcdcat, int *norecs, slen_t _cinstr_len);
void      zcatdr_(char *cdref, int *ndref, slen_t _cdref_len);
void      zcatfi_(int *ifltab, int *lextnd, int *lselca, int *lcdcat, int *ltonly, int *lerr);
void      zcatit_(int *ifltab, int *iunit, int *lselca, int *lcdcat, char *cinstr, int *lerr, slen_t _cinstr_len);
void      zcatlg_(int *ifltab, int *icunit, int *inunit, char *cinstr, int *ibeg, int *ilen, int *labrev, int *ldosrt, int *norecs, slen_t _cinstr_len);
void      zcheck_(int *ifltab, char *cpath, int *npath, int *nhead, int *ndata, int *lfound, slen_t _cpath_len);
void      zchkpn_(char *cpath, int *npath, int *istat, slen_t _cpath_len);
void      zcklnk_(int *ifltab, int *nerror);
void      zckmul_(int *ifltab);
void      zckpat_(int *ifltab, int *nerror);
void      zckpdd_(int *ifltab, int *instr, int *nfixed, int *istat);
void      zckpnb_(int *ifltab, int *nerror);
void      zclose_(int *ifltab);
void      zcofil_(int *iftold, int *iftnew, int *iarray, int *karray, int *ibuff, int *kbuff, int *lrcdel, int *lretag);
void      zcorec_(int *iftold, int *iftnew, char *cpold, char *cpnew, int *ibuff1, int *kbuff1, int *ibuff2, int *kbuff2, int *istat, slen_t _cpold_len, slen_t _cpnew_len);
void      zcut_(int *ifltab, char *cpath, int *ldelete, int *ibuffer, int *maxbuff, int *istatus, slen_t _cpath_len);
void      zcutsz_(int *ifltab, char *cpath, int *isize, int *istatus, slen_t _cpath_len);
void      zdblook_(int *ifltab, int *iadd, int *ilen);
void      zdbmod_(int *ifltab, int *iadd, int *ivalue, char *cvalue, int *lusech, slen_t _cvalue_len);
void      zdcinf_(int *jcomp, float *base, int *lbase, int *isize, int *idcpre, int *istat);
void      zdebug1_(int *ival, long_long *ival8, char *crval, char *cstrng, int *ibytes, slen_t _crval_len, slen_t _cstrng_len);
void      zdebug_(int *munit, int *iarray, int *iadd, int *ilen);
void      zdelet_(int *ifltab, char *cpath, int *npath, int *lfound, slen_t _cpath_len);
void      zdswap_(int *iarray, int *nwords);
void      zdtype_(int *ifltab, char *cpath, int *ndata, int *lfound, char *cdtype, int *idtype, slen_t _cpath_len, slen_t _cdtype_len);
void      zerror_(int *ifltab, int *jerr, char *csub, int *istat, int *iadd, char *cstr1, int *nstr1, char *cstr2, int *nstr2, slen_t _csub_len, slen_t _cstr1_len, slen_t _cstr2_len);
void      zfilst_(int *ifltab);
void      zfname_(char *cin, char *cname, int *nname, int *lexist, slen_t _cin_len, slen_t _cname_len);
void      zfpn_(char *ca, int *na, char *cb, int *nb, char *cc, int *nc, char *cd, int *nd, char *ce, int *ne, char *cf, int *nf, char *cpath, int *npath, slen_t _ca_len, slen_t _cb_len, slen_t _cc_len, slen_t _cd_len, slen_t _ce_len, slen_t _cf_len, slen_t _cpath_len);
void      zfsize_(int *ifltab);
void      zfver_(char *cfname, char *cver, int *iver, slen_t _cfname_len, slen_t _cver_len);
void      zgetad_(int *iadd, int *irec, int *iwrd);
void      zgetag_(int *ifltab, char *cpath, char *ctag, slen_t _cpath_len, slen_t _ctag_len);
void      zgetci_(int *ifltab, char *cparti, int *jcomp, float *dbase, int *ldbase, int *ldhigh, int *npre, slen_t _cparti_len);
void      zgetrw_(int *iadd, int *irec, int *iwrd);
void      zgintl_(int *intl, char *chintl, int *nodata, int *istat, slen_t _chintl_len);
void      zgirts_(int *ifltab, char *cpath, int *npath, int *juls, int *istime, int *jule, int *ietime, int *ibuff, int *kbuff, int *idum, int *ndum, int *kvals, float *dates, float *values, int *nvals, float *bdate, char *cunits, char *ctype, int *istat, slen_t _cpath_len, slen_t _cunits_len, slen_t _ctype_len);
void      zgpnp_(char *cline, char *ca, char *cb, char *cc, char *cd, char *ce, char *cf, int *nparts, slen_t _cline_len, slen_t _ca_len, slen_t _cb_len, slen_t _cc_len, slen_t _cd_len, slen_t _ce_len, slen_t _cf_len);
void      zgtags_(int *ifltab, char *cline, int *istat, slen_t _cline_len);
void      zgtdts_(int *ifltab, char *ca, int *na, char *cb, int *nb, char *cc, int *nc, char *cf, int *nf, int *juls, int *istime, int *jule, int *ietime, int *intl, int *ihead, int *nhead, int *iofset, float *values, int *nvals, char *cunits, char *ctype, int *istat, slen_t _ca_len, slen_t _cb_len, slen_t _cc_len, slen_t _cf_len, slen_t _cunits_len, slen_t _ctype_len);
void      zgtpfd_(int *ifltab, char *cpath, int *npath, int *nord, int *ncurve, int *ihoriz, char *c1unit, char *c2unit, char *c1type, char *c2type, char *clabel, int *klabel, int *nlabel, int *ibuff, int *kbuff, int *nbuff, float *values, int *kvals, int *nvals, int *istat, slen_t _cpath_len, slen_t _c1unit_len, slen_t _c2unit_len, slen_t _c1type_len, slen_t _c2type_len, slen_t _clabel_len);
void      zgtrec_(int *ifltab, int *iarray, int *narray, int *jadd, int *lsaveb);
void      zhash_(char *cpath, int *npath, int *max, int *ihash, slen_t _cpath_len);
void      zincbk_(int *iblock, int *jul, int *iyr, int *imon, int *iday);
void      zinit_(void);
void      zinqir_(int *ifltab, char *cflg, char *calpha, int *inumb, slen_t _cflg_len, slen_t _calpha_len);
void      zintbk_(float *data, int *nsd, int *ned, int *juls, int *istime, int *intd, int *ndinws, float *wrkspc, int *ndata, int *julswk, int *intlw, float *ofsetw, int *istat, int *iflag);
void      zirbeg_(int *ifltab, int *jul, char *ce, int *iyr, int *imon, int *iday, int *iblock, int *minblk, int *incblk, slen_t _ce_len);
void      zircpy_(int *jarray, int *jtime, float *dvalues, float *svalues, int *jqual, int *ipos, int *ldouble, int *lsqual, int *lrqual, int *lstore, int *ldswap);
void      zirdbl_(int *ifrom, int *ito, int *ltodbl);
void      zirdow_(int *icur, int *npairs, int *ndown, int *imult, int *ibuff);
void      zloadcache_(int *ifltab, int *istat);
void      zmatca_(char *cpath, int *ibpart, int *iepart, int *ilpart, char *ccdate, char *ccprog, int *lmatch, slen_t _cpath_len, slen_t _ccdate_len, slen_t _ccprog_len);
void      zmaxpart_(int *ifltab, int *imxpart);
void      zmin2r_(int *idates, float *dates, float *bdate, int *nvals);
void      zmovbk_(float *svalues, double *dvalues, int *ldouble, int *lfildob, int *jqual, int *lqvals, int *lqblok, int *nstart, int *nvals, int *juls, int *istime, int *intl, float *block, double *dblock, int *iblock, int *ndata, int *julsd, int *istat, int *iflag);
void      zmovwd_(int *ifrom, int *ito, int *number);
void      zmultu_(int *ifltab, int *lock, int *lflush);
void      zndata_(int *ifltab, int *ifpos, int *juls, int *isecs, char *cpath, int *npath, int *juld, int *isecd, int *idtype, int *istat, slen_t _cpath_len);
void      znextts_(int *ifltab, char *cpath, char *cnext, int *lforward, int *istat, slen_t _cpath_len, slen_t _cnext_len);
void      znwbin_(int *ifltab);
void      znwrit_(int *ifltab, char *cpath, int *npath, int *nihead, int *nchead, int *nuhead, int *ndata, slen_t _cpath_len);
void      zofset_(int *julian, int *itime, int *interval, int *iflag, int *iofset);
void      zopcat_(char *cdssfi, char *catfil, int *icunit, int *lopen, int *lcatlg, int *lcreat, int *nrec, slen_t _cdssfi_len, slen_t _catfil_len);
void      zopen_(int *ifltab, char *cfname, int *istat, slen_t _cfname_len);
void      zopnca_(char *cdssfi, int *icunit, int *lgenca, int *lopnca, int *lcatca, int *icdunt, int *lgencd, int *lopncd, int *lcatcd, int *nrecs, slen_t _cdssfi_len);
void      zordpn_(int *lselca, int *lerr);
void      zowrit_(int *ifltab, char *cpath, int *npath, int *nihead, int *nchead, int *nuhead, int *ndata, slen_t _cpath_len);
void      zpaste_(int *ifltab, int *ibuffer, int *istatus);
void      zpath_(char *ca, char *cb, char *cc, char *cd, char *ce, char *cf, char *cpath, int *npath, slen_t _ca_len, slen_t _cb_len, slen_t _cc_len, slen_t _cd_len, slen_t _ce_len, slen_t _cf_len, slen_t _cpath_len);
void      zpirts_(int *ifltab, char *cpath, int *npath, int *ibuff, int *kbuff, int *idum, int *ndum, float *dates, float *values, int *nvals, float *bdate, char *cunits, char *ctype, int *inflag, int *istat, slen_t _cpath_len, slen_t _cunits_len, slen_t _ctype_len);
void      zplist_(int *ifltab, char *cinstr, int *ifpos, char *cpath, int *npath, int *istat, slen_t _cinstr_len, slen_t _cpath_len);
void      zprtc_(int *munit, int *ibuff, int *next);
void      zprtci_(int *ifltab, int *lall, char *cparts, slen_t _cparts_len);
void      zptdts_(int *ifltab, char *ca, int *na, char *cb, int *nb, char *cc, int *nc, char *cf, int *nf, int *juls, int *istime, int *jule, int *ietime, int *intl, int *ihead, int *nhead, float *buff, float *values, int *nvals, char *cunits, char *ctype, int *istat, slen_t _ca_len, slen_t _cb_len, slen_t _cc_len, slen_t _cf_len, slen_t _cunits_len, slen_t _ctype_len);
void      zptpfd_(int *ifltab, char *cpath, int *npath, int *nord, int *ncurve, int *ihoriz, char *c1unit, char *c2unit, char *c1type, char *c2type, char *clabel, int *klabel, int *nlabel, int *ibuff, int *kbuff, int *nbuff, float *values, int *kvals, int *nvals, int *iplan, int *istat, slen_t _cpath_len, slen_t _c1unit_len, slen_t _c2unit_len, slen_t _c1type_len, slen_t _c2type_len, slen_t _clabel_len);
void      zptrec_(int *ifltab, int *iarray, int *narray, int *jadd, int *lsaveb);
void      zquery_(char *cflg, char *calpha, int *inumb, slen_t _cflg_len, slen_t _calpha_len);
void      zr2min_(int *idates, float *dates, int *jdate, int *nvals);
void      zrdbuf_(int *ifltab, char *cpath, int *ihbuff, int *khbuff, int *nhbuff, int *idbuff, int *kdbuff, int *ndbuff, int *lend, int *iplan, int *lfound, slen_t _cpath_len);
void      zrdcat_(int *iunit, int *lall, int *junit, char *ctags, int *ntags, char *cpath, int *npath, int *nfound, slen_t _ctags_len, slen_t _cpath_len);
void      zrdinf_(int *ifltab, char *cpath, int *nhead, int *ndata, int *istat, slen_t _cpath_len);
void      zrdpat_(int *iunit, int *ipos, int *inumb, char *ctag, char *cpath, int *npath, int *lend, slen_t _ctag_len, slen_t _cpath_len);
void      zrdpn_(int *iunit, int *ipos, int *inumb, char *cpath, int *npath, slen_t _cpath_len);
void      zrdprm_(int *ifltab, int *lsave);
void      zread_(int *ifltab, char *cpath, int *npath, int *ihead, int *nhead, int *idata, int *ndata, int *iplan, int *lfound, slen_t _cpath_len);
void      zreadx_(int *ifltab, char *cpath, int *iihead, int *kihead, int *nihead, int *ichead, int *kchead, int *nchead, int *iuhead, int *kuhead, int *nuhead, int *idata, int *kdata, int *ndata, int *iplan, int *lfound, slen_t _cpath_len);
void      zrecin_(int *ifltab, int *iout, int *ilevel, char *cpath, int *ibuff, int *kbuff, int *lfound, slen_t _cpath_len);
void      zrenam_(int *ifltab, char *cpatho, int *npatho, char *cpathn, int *npathn, int *lfound, slen_t _cpatho_len, slen_t _cpathn_len);
void      zretag_(int *ifltab, char *cpath, int *npath, char *ctag, int *lfound, slen_t _cpath_len, slen_t _ctag_len);
void      zrinfo_(int *ifltab, char *cpath, int *lfound, int *idtype, char *cdtype, int *ldoub, int *lqual, int *iprecis, char *crtag, char *clwdate, char *clwtime, char *cpname, int *ivers, int *ndata, int *nspace, int *icompres, int *lpass, slen_t _cpath_len, slen_t _cdtype_len, slen_t _crtag_len, slen_t _clwdate_len, slen_t _clwtime_len, slen_t _cpname_len);
void      zrits_(int *ifltab, char *cpath, int *juls, int *istime, int *jule, int *ietime, int *itimes, float *values, int *kvals, int *nvals, int *ibdate, char *cunits, char *ctype, int *istat, slen_t _cpath_len, slen_t _cunits_len, slen_t _ctype_len);
void      zritsc_(int *ifltab, char *cpath, int *juls, int *istime, int *jule, int *ietime, int *lgetdob, int *lfildob, int *itimes, float *svalues, double *dvalues, int *kvals, int *nvals, int *ibdate, int *iqual, int *lqual, int *lqread, char *cunits, char *ctype, char *csupp, int *itzone, char *ctzone, double *coords, int *icdesc, int *lcoords, int *inflag, int *istat, slen_t _cpath_len, slen_t _cunits_len, slen_t _ctype_len, slen_t _csupp_len, slen_t _ctzone_len);
void      zritsi_(int *ifltab, char *cpath, int *juls, int *istime, int *jule, int *ietime, int *lgetdob, int *lfildob, int *itimes, float *svalues, double *dvalues, int *kvals, int *nvals, int *ibdate, int *iqual, int *lqual, int *lqread, char *cunits, char *ctype, int *iuhead, int *kuhead, int *nuhead, double *coords, int *icdesc, int *lcoords, int *inflag, int *istat, slen_t _cpath_len, slen_t _cunits_len, slen_t _ctype_len);
void      zritsx_(int *ifltab, char *cpath, int *juls, int *istime, int *jule, int *ietime, int *itimes, float *svalues, int *kvals, int *nvals, int *ibdate, int *iqual, int *lqual, int *lqread, char *cunits, char *ctype, int *iuhead, int *kuhead, int *nuhead, int *inflag, int *istat, slen_t _cpath_len, slen_t _cunits_len, slen_t _ctype_len);
void      zritsxd_(int *ifltab, char *cpath, int *juls, int *istime, int *jule, int *ietime, int *itimes, double *dvalues, int *kvals, int *nvals, int *ibdate, int *iqual, int *lqual, int *lqread, char *cunits, char *ctype, int *iuhead, int *kuhead, int *nuhead, int *inflag, int *istat, slen_t _cpath_len, slen_t _cunits_len, slen_t _ctype_len);
void      zrmem_(int *iunit, int *irec, int *iarray, int *nwords, int *istat);
void      zrpd_(int *ifltab, char *cpath, int *nord, int *ncurve, int *ihoriz, char *c1unit, char *c1type, char *c2unit, char *c2type, float *svalues, int *kvals, int *nvals, char *clabel, int *klabel, int *label, int *iuhead, int *kuhead, int *nuhead, int *istat, slen_t _cpath_len, slen_t _c1unit_len, slen_t _c1type_len, slen_t _c2unit_len, slen_t _c2type_len, slen_t _clabel_len);
void      zrpdd_(int *ifltab, char *cpath, int *nord, int *ncurve, int *ihoriz, char *c1unit, char *c1type, char *c2unit, char *c2type, double *dvalues, int *kvals, int *nvals, char *clabel, int *klabel, int *label, int *iuhead, int *kuhead, int *nuhead, int *istat, slen_t _cpath_len, slen_t _c1unit_len, slen_t _c1type_len, slen_t _c2unit_len, slen_t _c2type_len, slen_t _clabel_len);
void      zrpdi_(int *ifltab, char *cpath, int *nord, int *ncurve, int *ihoriz, char *c1unit, char *c1type, char *c2unit, char *c2type, float *svalues, double *dvalues, int *ldouble, int *kvals, int *nvals, char *clabel, int *klabel, int *label, int *iuhead, int *kuhead, int *nuhead, int *istat, slen_t _cpath_len, slen_t _c1unit_len, slen_t _c1type_len, slen_t _c2unit_len, slen_t _c2type_len, slen_t _clabel_len);
void      zrrec_(int *iunit, int *irec, int *iarray, int *nwords, int *iswap, int *istat, int *jstat);
void      zrrst_(int *ifltab, char *cpath, int *ietim, char *cloc, char *catim, char *chparm, char *chunit, char *cfparm, char *cfunit, char *ccmt, char *copt, int *lsnum, int *isnum, int *ldatum, float *datum, int *lstage, int *ibhi, int *ibhu, float *huv, int *ibho, float *hov, int *ibfi, int *ibfu, float *fuv, int *ibfo, float *fov, int *kbase, int *nbase, float *height, float *flow, int *kshift, int *nshift, int *isti, int *istu, int *isto, int *isbi, int *isbu, float *sbuv, int *isbo, float *sbov, int *ishi, int *ishu, float *shuv, int *isho, float *shov, int *latmsk, int *jbdate, int *ietime, int *iatime, int *nshftp, int *kshval, int *nshval, float *shifts, int *lcoff, float *cofval, int *koff, int *noff, int *iobi, int *iobu, float *obuv, int *iobo, float *obov, int *iohi, int *iohu, float *ohuv, int *ioho, float *ohov, float *offset, int *ihoriz, int *istat, slen_t _cpath_len, slen_t _cloc_len, slen_t _catim_len, slen_t _chparm_len, slen_t _chunit_len, slen_t _cfparm_len, slen_t _cfunit_len, slen_t _ccmt_len, slen_t _copt_len);
void      zrrsti_(int *ifltab, char *cpath, int *ifcat, int *iintrp, int *iuflow, int *ioflow, int *lfound, int *ktimes, int *ntimes, int *itimes, int *istat, slen_t _cpath_len);
void      zrrtpa_(int *ifltab, char *cpath, float *values, int *nvals, char *cunits, char *ctype, int *iuhead, int *kheadu, int *nuhead, int *istat, slen_t _cpath_len, slen_t _cunits_len, slen_t _ctype_len);
void      zrrts_(int *ifltab, char *cpath, char *cdate, char *ctime, int *nvals, float *values, char *cunits, char *ctype, int *iofset, int *istat, slen_t _cpath_len, slen_t _cdate_len, slen_t _ctime_len, slen_t _cunits_len, slen_t _ctype_len);
void      zrrtsb_(int *ifltab, int *juls, int *istime, int *intl, int *julsd, int *nstart, int *nldata, int *nadata, int *nvals, int *lgetdob, int *lfildob, float *svalues, double *dvalues, int *jqual, int *lqblok, int *lqual, int *jcomp, int *lfound, int *istat);
void      zrrtsc_(int *ifltab, char *cpath, char *cdate, char *ctime, int *kvals, int *nvals, int *lgetdob, int *lfildob, float *svalues, double *dvalues, int *jqual, int *lqual, int *lqread, char *cunits, char *ctype, char *csupp, int *iofset, int *jcomp, int *itzone, char *ctzone, double *coords, int *icdesc, int *lcoords, int *istat, slen_t _cpath_len, slen_t _cdate_len, slen_t _ctime_len, slen_t _cunits_len, slen_t _ctype_len, slen_t _csupp_len, slen_t _ctzone_len);
void      zrrtsi_(int *ifltab, char *cpath, char *crdate, char *crtime, int *kvals, int *nvals, int *lgetdob, int *lfildob, float *svalues, double *dvalues, int *jqual, int *lqual, int *lqread, char *cunits, char *ctype, int *iuhead, int *kuhead, int *nuhead, int *iofset, int *jcomp, double *coords, int *icdesc, int *lcoords, int *istat, slen_t _cpath_len, slen_t _crdate_len, slen_t _crtime_len, slen_t _cunits_len, slen_t _ctype_len);
void      zrrtsx_(int *ifltab, char *cpath, char *cdate, char *ctime, int *nvals, float *svalues, int *jqual, int *lqual, int *lqread, char *cunits, char *ctype, int *iuhead, int *kuhead, int *nuhead, int *iofset, int *jcomp, int *istat, slen_t _cpath_len, slen_t _cdate_len, slen_t _ctime_len, slen_t _cunits_len, slen_t _ctype_len);
void      zrrtsxd_(int *ifltab, char *cpath, char *cdate, char *ctime, int *nvals, double *dvalues, int *jqual, int *lqual, int *lqread, char *cunits, char *ctype, int *iuhead, int *kuhead, int *nuhead, int *iofset, int *jcomp, int *istat, slen_t _cpath_len, slen_t _cdate_len, slen_t _ctime_len, slen_t _cunits_len, slen_t _ctype_len);
void      zrtall_(int *ifltab);
void      zrtext_(int *ifltab, char *cpath, int *iunit, int *iuhead, int *kuhead, int *nuhead, int *lccntl, int *nlines, int *istat, slen_t _cpath_len);
void      zrtxta_(int *ifltab, char *cpath, char *carray, int *karray, int *nlines, int *iuhead, int *kuhead, int *nuhead, int *istat, slen_t _cpath_len, slen_t _carray_len);
void      zrtxts_(int *ifltab, char *cpath, char *cstring, int *kstring, int *nstring, int *iuhead, int *kuhead, int *nuhead, int *istat, slen_t _cpath_len, slen_t _cstring_len);
void      zscomp_(int *icomp, float *base, int *lbase, int *lhigh, int *npre);
void      zselca_(char *cpath, int *npath, char *cctag, char *ccprog, char *ccdate, char *cctime, char *cdtype, int *idtype, int *irvers, int *ndata, int *nhead, int *jnpath, int *lselca, int *lmatch, int *lcdcat, int *lerr, slen_t _cpath_len, slen_t _cctag_len, slen_t _ccprog_len, slen_t _ccdate_len, slen_t _cctime_len, slen_t _cdtype_len);
void      zset_(char *cflg, char *cstr, int *numb, slen_t _cflg_len, slen_t _cstr_len);
void      zsetca_(char *cinstr, int *lselca, slen_t _cinstr_len);
void      zsetci_(int *ifltab, char *cpart, int *lpart, int *jcomp, float *dbase, int *ldbase, int *ldhigh, int *npre, int *istat, slen_t _cpart_len);
void      zsetfi_(int *ifltab, char *cparam, char *calpha, int *inumb, int *istatus, slen_t _cparam_len, slen_t _calpha_len);
void      zsetpr_(int *ifltab, char *cflg, char *cstr, int *inumb, slen_t _cflg_len, slen_t _cstr_len);
void      zsits_(int *ifltab, char *cpath, int *itimes, float *values, int *nvals, int *ibdate, char *cunits, char *ctype, int *inflag, int *istat, slen_t _cpath_len, slen_t _cunits_len, slen_t _ctype_len);
void      zsitsc_(int *ifltab, char *cpath, int *itimes, float *values, double *dvalues, int *ldouble, int *nvalue, int *ibdate, int *jqual, int *lsqual, char *cunits, char *ctype, double *coords, int *ncoords, int *icdesc, int *ncdesc, char *csupp, int *itzone, char *ctzone, int *inflag, int *istat, slen_t _cpath_len, slen_t _cunits_len, slen_t _ctype_len, slen_t _csupp_len, slen_t _ctzone_len);
void      zsitsi_(int *ifltab, char *cpath, int *itimes, float *svalues, double *dvalues, int *ldouble, int *nvalue, int *ibdate, int *jqual, int *lsqual, char *cunits, char *ctype, int *iuhead, int *nuhead, double *coords, int *ncoords, int *icdesc, int *ncdesc, int *inflag, int *istat, slen_t _cpath_len, slen_t _cunits_len, slen_t _ctype_len);
void      zsitsx_(int *ifltab, char *cpath, int *itimes, float *values, int *nvalue, int *ibdate, int *jqual, int *lsqual, char *cunits, char *ctype, int *iuhead, int *nuhead, int *inflag, int *istat, slen_t _cpath_len, slen_t _cunits_len, slen_t _ctype_len);
void      zsitsxd_(int *ifltab, char *cpath, int *itimes, double *dvalues, int *nvalue, int *ibdate, int *jqual, int *lsqual, char *cunits, char *ctype, int *iuhead, int *nuhead, int *inflag, int *istat, slen_t _cpath_len, slen_t _cunits_len, slen_t _ctype_len);
void      zspd_(int *ifltab, char *cpath, int *nord, int *ncurve, int *ihoriz, char *c1unit, char *c1type, char *c2unit, char *c2type, float *svalues, char *clabel, int *label, int *iuhead, int *nuhead, int *iplan, int *istat, slen_t _cpath_len, slen_t _c1unit_len, slen_t _c1type_len, slen_t _c2unit_len, slen_t _c2type_len, slen_t _clabel_len);
void      zspdd_(int *ifltab, char *cpath, int *nord, int *ncurve, int *ihoriz, char *c1unit, char *c1type, char *c2unit, char *c2type, double *dvalues, char *clabel, int *label, int *iuhead, int *nuhead, int *iplan, int *istat, slen_t _cpath_len, slen_t _c1unit_len, slen_t _c1type_len, slen_t _c2unit_len, slen_t _c2type_len, slen_t _clabel_len);
void      zspdi_(int *ifltab, char *cpath, int *nord, int *ncurve, int *ihoriz, char *c1unit, char *c1type, char *c2unit, char *c2type, float *svalues, double *dvalues, int *ldouble, char *clabel, int *label, int *iuhead, int *nuhead, int *iplan, int *istat, slen_t _cpath_len, slen_t _c1unit_len, slen_t _c1type_len, slen_t _c2unit_len, slen_t _c2type_len, slen_t _clabel_len);
void      zsqprm_(int *iftold, int *iftnew, int *lretag);
void      zsrst_(int *ifltab, char *cpath, char *cloc, char *catim, char *chparm, char *chunit, char *cfparm, char *cfunit, char *ccmt, char *copt, int *lsnum, int *isnum, int *ldatum, float *datum, int *lstage, int *ibhi, int *ibhu, float *huv, int *ibho, float *hov, int *ibfi, int *ibfu, float *fuv, int *ibfo, float *fov, int *nbase, float *height, float *flow, int *nshift, int *isti, int *istu, int *isto, int *isbi, int *isbu, float *sbuv, int *isbo, float *sbov, int *ishi, int *ishu, float *shuv, int *isho, float *shov, int *latmsk, int *jbdate, int *ietime, int *iatime, int *nshftp, float *shifts, int *lcoff, float *cofval, int *noff, int *iobi, int *iobu, float *obuv, int *iobo, float *obov, int *iohi, int *iohu, float *ohuv, int *ioho, float *ohov, float *offset, int *ihoriz, int *iplan, int *istat, slen_t _cpath_len, slen_t _cloc_len, slen_t _catim_len, slen_t _chparm_len, slen_t _chunit_len, slen_t _cfparm_len, slen_t _cfunit_len, slen_t _ccmt_len, slen_t _copt_len);
void      zsrsti_(int *ifltab, char *cpath, int *iintrp, int *iuflow, int *ioflow, int *iplan, int *istat, slen_t _cpath_len);
void      zsrtpa_(int *ifltab, char *cpath, float *values, int *nvals, char *cunits, char *ctype, int *iuhead, int *nuhead, int *iplan, int *istat, slen_t _cpath_len, slen_t _cunits_len, slen_t _ctype_len);
void      zsrts_(int *ifltab, char *cpath, char *cdate, char *ctime, int *nvals, float *values, char *cunits, char *ctype, int *iplan, int *istat, slen_t _cpath_len, slen_t _cdate_len, slen_t _ctime_len, slen_t _cunits_len, slen_t _ctype_len);
void      zsrtsc_(int *ifltab, char *cpath, char *cdate, char *ctime, int *nvals, int *ldouble, float *values, double *dvalues, int *jqual, int *lqual, char *cunits, char *ctype, double *coords, int *ncoords, int *icdesc, int *ncdesc, char *csupp, int *itzone, char *ctzone, int *iplan, int *jcomp, float *basev, int *lbasev, int *ldhigh, int *nprec, int *istat, slen_t _cpath_len, slen_t _cdate_len, slen_t _ctime_len, slen_t _cunits_len, slen_t _ctype_len, slen_t _csupp_len, slen_t _ctzone_len);
void      zsrtsi_(int *ifltab, char *cpath, char *cdate, char *ctime, int *nvals, int *ldouble, float *svalues, double *dvalues, int *jqual, int *lqual, char *cunits, char *ctype, int *iuhead, int *nuhead, double *coords, int *ncoords, int *icdesc, int *ncdesc, int *iplan, int *jcomp, float *basev, int *lbasev, int *ldhigh, int *nprec, int *istat, slen_t _cpath_len, slen_t _cdate_len, slen_t _ctime_len, slen_t _cunits_len, slen_t _ctype_len);
void      zsrtsx_(int *ifltab, char *cpath, char *cdate, char *ctime, int *nvals, float *values, int *jqual, int *lqual, char *cunits, char *ctype, int *iuhead, int *nuhead, int *iplan, int *jcomp, float *basev, int *lbasev, int *ldhigh, int *nprec, int *istat, slen_t _cpath_len, slen_t _cdate_len, slen_t _ctime_len, slen_t _cunits_len, slen_t _ctype_len);
void      zsrtsxd_(int *ifltab, char *cpath, char *cdate, char *ctime, int *nvals, double *dvalues, int *jqual, int *lqual, char *cunits, char *ctype, int *iuhead, int *nuhead, int *iplan, int *jcomp, float *basev, int *lbasev, int *ldhigh, int *nprec, int *istat, slen_t _cpath_len, slen_t _cdate_len, slen_t _ctime_len, slen_t _cunits_len, slen_t _ctype_len);
void      zstags_(int *ifltab, char *cline, int *istat, slen_t _cline_len);
void      zstext_(int *ifltab, char *cpath, int *iunit, int *iuhead, int *nuhead, int *nlines, int *istat, slen_t _cpath_len);
void      zstfh_(char *clabel, char *citem, int *nitem, int *ihead, int *khead, int *nhead, int *ierr, slen_t _clabel_len, slen_t _citem_len);
void      zstxta_(int *ifltab, char *cpath, char *carray, int *narray, int *iuhead, int *nuhead, int *istat, slen_t _cpath_len, slen_t _carray_len);
void      zswap_(int *in, int *iout);
void      zswapw_(int *idata, int *ndata);
void      ztagfi_(int *ifltab, int *ifun, int *nrecs, int *itag, int *jhash);
void      ztagpa_(int *ifltab, int *junit, char *ctags, int *ntags, char *cpath, int *npath, int *nfound, slen_t _ctags_len, slen_t _cpath_len);
void      ztsends_(int *ifltab, char *cpath, int *isearch, int *juls, int *istime, int *jule, int *ietime, int *lfound, slen_t _cpath_len);
void      ztsinfo_(int *ifltab, char *cpath, int *juls, int *istime, int *jule, int *ietime, char *cunits, char *ctype, int *lqual, int *ldouble, int *lfound, slen_t _cpath_len, slen_t _cunits_len, slen_t _ctype_len);
void      ztsint_(int *ifltab, char *ca, int *na, char *cb, int *nb, char *cc, int *nc, char *cf, int *nf, int *julis, int *isitim, int *jule, int *ietime, int *intin, int *intout, int *ihead, int *nh, float *wrkspc, float *values, int *nvals, char *cunits, char *ctype, int *istat, slen_t _ca_len, slen_t _cb_len, slen_t _cc_len, slen_t _cf_len, slen_t _cunits_len, slen_t _ctype_len);
void      ztsrange_(int *ifltab, char *cpath, int *isearch, char *cfirstp, char *clastp, int *nfound, slen_t _cpath_len, slen_t _cfirstp_len, slen_t _clastp_len);
void      ztssrch_(int *ifltab, char *cinpath, int *iunit, char *coutpath, int *nfound, slen_t _cinpath_len, slen_t _coutpath_len);
int       ztstqp_(int *qualwd);
void      zudall_(int *ifltab, int *junit);
void      zudava_(int *ifltab, char *cpath, int *istatus, slen_t _cpath_len);
void      zufpn_(char *ca, int *na, char *cb, int *nb, char *cc, int *nc, char *cd, int *nd, char *ce, int *ne, char *cf, int *nf, char *cpath, int *npath, int *istat, slen_t _ca_len, slen_t _cb_len, slen_t _cc_len, slen_t _cd_len, slen_t _ce_len, slen_t _cf_len, slen_t _cpath_len);
void      zundel_(int *ifltab, char *cpath, int *npath, int *istat, slen_t _cpath_len);
void      zupath_(char *cpath, int *ibpart, int *iepart, int *ilpart, int *istat, slen_t _cpath_len);
void      zuprts_(int *ifltab, int *juls, int *istime, int *intl, int *julsd, int *nstart, int *ndata, int *nvals, float *values, int *jqual, int *lqual, int *iplan, int *lerr);
void      zustfh_(char *clabel, char *citem, int *nitem, int *ipos, int *ihead, int *nhead, int *ierr, slen_t _clabel_len, slen_t _citem_len);
void      zwlock_(int *ifltab, char *cact, int *istat, slen_t _cact_len);
void      zwmem_(int *iunit, int *irec, int *iarray, int *nwords, int *istat);
void      zwrbuf_(int *ifltab, char *cpath, int *ihead, int *nhead, int *nthead, int *idata, int *ndata, int *ntdata, int *lend, slen_t _cpath_len);
void      zwrec_(int *iunit, int *irec, int *iarray, int *nwords, int *iswap, int *istat, int *jstat);
void      zwrite_(int *ifltab, char *cpath, int *npath, int *iuhead, int *nuhead, int *idata, int *ndata, int *iplan, int *lfound, slen_t _cpath_len);
void      zwritx_(int *ifltab, char *cpath, int *npath, int *iihead, int *nihead, int *ichead, int *nchead, int *iuhead, int *nuhead, int *idata, int *ndata, int *jtype, int *iplan, int *istat, int *lfound, slen_t _cpath_len);

/*------------------------*/
/* Non-supported routines */
/*------------------------*/
#ifdef UNSUPPORTED
void      etime_(void);
void      scnpuf_(char *m, char *csname, int *if34, int *irecsc, int *ncol, int *nrows, int *irow, int *icol, int *istat, slen_t _m_len, slen_t _csname_len);
#endif

/*----------------*/
/* C/C++ Routines */
/*----------------*/
void      chmodf_(char *path, int *mode, int *istat, int l_path);
void      closf_(int *ihandle, int *istat);
void      fildat_(char *cname, char *cfdate, char *cftime, int *istat, int l_cname, int l_cfdate, int l_cftime);
void      filen64_(char *cmask, int *ifatt, char *cmode, char *cfname, long_long *ifsize, char *cfdate, char *cftime, int *iatt, int *istat, int l_cmask, int l_cmode, int l_cfname, int l_cfdate, int l_cftime);
void      filen_(char *cmask, int *ifatt, char *cmode, char *cfname, int *ifsize, char *cfdate, char *cftime, int *iatt, int *istat, int l_cmask, int l_cmode, int l_cfname, int l_cfdate, int l_cftime);
void      filesize64_(int *handle, long_long *nbytes);
void      filesize_(int *handle, int *nbytes);
void      filesizen64_(char *filename, long_long *nbytes, int *status, int filename_len);
void      filesizen_(char *filename, int *nbytes, int *status, int filename_len);
void      filesort_(char *inname, char *outname, int *maxlinewidth, int *maxlines, int *status, int inname_len, int outname_len);
void      flushf_(int *ihandle, int *istat);
void      getpid_(int *pid);
void      getprocid_(int *pid);
void      gtenv_(char *cname, char *cenv, int *nenv, int *istat, int lcname, int lcenv);
void      ioread_(int *iport, char *carray, int *maxary, int *narray);
void      iowrite_(int *iport, char *carray, int *narray, int *ierr, int lcarray);
void      isonlocaldrive_(char *pathname, int *islocal, int len_pathname);
int       isUndefinedDbl(double value);
int       isundefineddbl_(double *value);
int       isUndefinedFlt(float value);
int       isundefinedflt_(float value);
int       isUndefinedInt(int value);
int       isundefinedint_(int value);
int       isUndefinedShrt(short value);
int       isundefinedshrt_(short value);
void      lockdss64_(int *ihandle, int *mode, long_long *position, long_long *nbytes, int *istat);
void      lockdss_(int *ihandle, int *mode, long *position, long *nbytes, int *istat);
void      lockf_(int *ihandle, int *lock, int *istat);
void      lockfr_(int *handle, int *istat);
void      lockfu_(int *handle, int *istat);
void      lockfw_(int *handle, int *istat);
int       lockFile(int ihandle, int mode, long position, long nbytes);
int       lockFile64(int ihandle, int mode, long_long position, long_long nbytes);
void      openf_(char *cname, int *iaccess, int *ihandle, int *istat, int len_cname);
void      permissions_(char *path, int *mode, int *istat, int l_path);
void      readf_(int *ihandl, void *buff, int *nbytes, int *istat, int *ntrans);
void      readmem_(int *mbuff, int *wordpos, int *intbuff, int *nwords);
void      reallocatemem_(int **buff, int *nbytes);
void      scncols_(int *columns);
void      scnlines_(int *lines);
//void      scnsize_(int *lines, int *columns);
void      seekf64_(int *ihandl, int *iorigin, long_long *iofset, long_long *ipos, int *istat);
void      seekf_(int *ihandl, int *iorigin, long *iofset, long *ipos, int *istat);
void      systim_(int *julian, int *sec);
double    undefinedDbl();
double    undefineddbl_();
double    undefinedFlt();
double    undefinedflt_();
double    undefinedInt();
double    undefinedint_();
double    undefinedShrt();
double    undefinedshrt_();
void      waits_(float *secs);
void      writemem_(int *mbuff, int *wordpos, int *intbuff, int *nwords);
void      writf_(int *ihandle, void *buff, int *nbytes, int *istat, int *ntrans);

/*--------------------------*/
/* Unix-only C/C++ Routines
#if !defined(_MSC_VER) && !defined(SWIGWIN)
void      getppid_(int *ppid);
void      iosave_(int *iunit, char *cset, int *istat, int l_cset);
void      ioset_(int *iunit, int *iwait, int *nchar, int *istat);
#endif
/*--------------------------*/

#ifdef __cplusplus
} // extern "C"
#endif

#endif /* __HECLIB_INCLUDED__ */
