# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.0
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError('Python 2.7 or later required')

# Import the low-level C/C++ module
if __package__ or '.' in __name__:
    from . import _pyheclib
else:
    import _pyheclib

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if name == "thisown":
        return self.this.own(value)
    if name == "this":
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if not static:
        object.__setattr__(self, name, value)
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if name == "thisown":
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)



def new_intp() -> "int *":
    return _pyheclib.new_intp()

def copy_intp(value: 'int') -> "int *":
    return _pyheclib.copy_intp(value)

def delete_intp(obj: 'int *') -> "void":
    return _pyheclib.delete_intp(obj)

def intp_assign(obj: 'int *', value: 'int') -> "void":
    return _pyheclib.intp_assign(obj, value)

def intp_value(obj: 'int *') -> "int":
    return _pyheclib.intp_value(obj)

def new_doublep() -> "double *":
    return _pyheclib.new_doublep()

def copy_doublep(value: 'double') -> "double *":
    return _pyheclib.copy_doublep(value)

def delete_doublep(obj: 'double *') -> "void":
    return _pyheclib.delete_doublep(obj)

def doublep_assign(obj: 'double *', value: 'double') -> "void":
    return _pyheclib.doublep_assign(obj, value)

def doublep_value(obj: 'double *') -> "double":
    return _pyheclib.doublep_value(obj)
class intArray(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, nelements: 'size_t'):
        _pyheclib.intArray_swiginit(self, _pyheclib.new_intArray(nelements))
    __swig_destroy__ = _pyheclib.delete_intArray

    def __getitem__(self, index: 'size_t') -> "int":
        return _pyheclib.intArray___getitem__(self, index)

    def __setitem__(self, index: 'size_t', value: 'int') -> "void":
        return _pyheclib.intArray___setitem__(self, index, value)

    def cast(self) -> "int *":
        return _pyheclib.intArray_cast(self)

    @staticmethod
    def frompointer(t: 'int *') -> "intArray *":
        return _pyheclib.intArray_frompointer(t)

# Register intArray in _pyheclib:
_pyheclib.intArray_swigregister(intArray)

def intArray_frompointer(t: 'int *') -> "intArray *":
    return _pyheclib.intArray_frompointer(t)

class doubleArray(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, nelements: 'size_t'):
        _pyheclib.doubleArray_swiginit(self, _pyheclib.new_doubleArray(nelements))
    __swig_destroy__ = _pyheclib.delete_doubleArray

    def __getitem__(self, index: 'size_t') -> "double":
        return _pyheclib.doubleArray___getitem__(self, index)

    def __setitem__(self, index: 'size_t', value: 'double') -> "void":
        return _pyheclib.doubleArray___setitem__(self, index, value)

    def cast(self) -> "double *":
        return _pyheclib.doubleArray_cast(self)

    @staticmethod
    def frompointer(t: 'double *') -> "doubleArray *":
        return _pyheclib.doubleArray_frompointer(t)

# Register doubleArray in _pyheclib:
_pyheclib.doubleArray_swigregister(doubleArray)

def doubleArray_frompointer(t: 'double *') -> "doubleArray *":
    return _pyheclib.doubleArray_frompointer(t)


def zcat_(ifltab: 'int *', icunit: 'int *', icdunt: 'int *', inunit: 'int *', cinstr: 'char *', labrev: 'int *', ldosrt: 'int *', lcdcat: 'int *', norecs: 'int *', _cinstr_len: 'slen_t') -> "void":
    return _pyheclib.zcat_(ifltab, icunit, icdunt, inunit, cinstr, labrev, ldosrt, lcdcat, norecs, _cinstr_len)

def fortranclose_(INPUT: 'int *') -> "int":
    return _pyheclib.fortranclose_(INPUT)

def fortranflush_(INPUT: 'int *') -> "void":
    return _pyheclib.fortranflush_(INPUT)

def fortranopen_(INPUT: 'int *', filename: 'char *', _filename_len: 'slen_t') -> "int":
    return _pyheclib.fortranopen_(INPUT, filename, _filename_len)

def zclose_(ifltab: 'int *') -> "void":
    return _pyheclib.zclose_(ifltab)

def hec_datjul(cdate: 'char *') -> "int *, int *":
    return _pyheclib.hec_datjul(cdate)

def hec_zinqir(ifltab: 'int *', cflg: 'char *', calpha: 'char *', inumb: 'int *') -> "char *":
    return _pyheclib.hec_zinqir(ifltab, cflg, calpha, inumb)

def hec_zset(cflg: 'char *', cstr: 'char *', numb: 'int *') -> "void":
    return _pyheclib.hec_zset(cflg, cstr, numb)

def hec_zgintl(intl: 'int *', chintl: 'char *', _chintl_len: 'slen_t', istat: 'int *') -> "int *, int *, int *":
    return _pyheclib.hec_zgintl(intl, chintl, _chintl_len, istat)

def hec_zopen(ifltab: 'int *', cfname: 'char *') -> "int *":
    return _pyheclib.hec_zopen(ifltab, cfname)

def hec_zsrtsxd(ifltab: 'int *', cpath: 'char *', cdate: 'char *', ctime: 'char *', numpyvalues: 'double *', cunits: 'char *', ctype: 'char *') -> "int *":
    return _pyheclib.hec_zsrtsxd(ifltab, cpath, cdate, ctime, numpyvalues, cunits, ctype)

def hec_zsitsxd(ifltab: 'int *', cpath: 'char *', itimes: 'int *', dvalues: 'double *', ibdate: 'int *', cunits: 'char *', ctype: 'char *', inflag: 'int *') -> "int *":
    return _pyheclib.hec_zsitsxd(ifltab, cpath, itimes, dvalues, ibdate, cunits, ctype, inflag)

def hec_zrrtsxd(ifltab: 'int *', cpath: 'char *', cdate: 'char *', ctime: 'char *', numpyvalues: 'double *') -> "char *, char *, int *, int *":
    return _pyheclib.hec_zrrtsxd(ifltab, cpath, cdate, ctime, numpyvalues)

def hec_zritsxd(ifltab: 'int *', cpath: 'char *', juls: 'int *', istime: 'int *', jule: 'int *', ietime: 'int *', itimes: 'int *', dvalues: 'double *', inflag: 'int *') -> "int *, int *, char *, char *, int *":
    return _pyheclib.hec_zritsxd(ifltab, cpath, juls, istime, jule, ietime, itimes, dvalues, inflag)


