{% set name = "pyhecdss" %}
{% set data = load_setup_py_data() %}

package:
  name:           "{{ name|lower }}"
  version:        "{{ data['version'] }}"

source:
  path: ..

build:
  number: 0
  #skip:           true

requirements:
  build:
    - python
    - setuptools
    - numpy {{ numpy }}
    - pandas >=0.23
    - pytest-runner >=5.0
    - swig

  run:
    - python >=3.5,<4.0
    - numpy  >=1.16
    - pandas >=0.23

test:
  imports:
    - pyhecdss
  source_files:
    - tests
  requires:
    - pytest
    - pytest-cov
  commands:
    - (setlocal && cd tests && pytest && endlocal) # [win]
    - (cd tests; pytest) # [unix]
about:
  home:           "https://github.com/CADWRDeltaModeling/pyhecdss"
  license:        "MIT"
  license_family: "MIT"
  summary:        "Read HECDSS timeseries as pandas DataFrame"
