{% set name = "pyhecdss" %}
{% set data = load_setup_py_data() %}

package:
  name:           "{{ name|lower }}"
  version:        "{{ data['version'] }}"

source:
  #git_url: http://dwrrhapp0179.ad.water.ca.gov/gitea/nsandhu/pyhecdss.git
  path: ..

build:
  number: 0
  #skip:           true
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - numpy {{ numpy }}
    - swig
    - pandas >=0.23
  run:
    - python >=3.7
    - numpy  >=1.11
    - pandas >=0.23

test:
  imports:
    - pyhecdss
  source_files:
    - tests
  requires:
    - pytest
    - pytest-cov
  commands:
    - (setlocal && cd tests && pytest && endlocal)
about:
  home:           "http://dwrrhapp0179.ad.water.ca.gov/gitea/nsandhu/pyhecdss"
  license:        "BSD"
  license_family: "BSD"
  summary:        "Read HECDSS as pandas DataFrame"
